-- PROJETO MYSQL BIBLIOTECAS
-- https://github.com/ErickVeronezi

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_BIBLIOTECA
FOREIGN KEY (FK_IDBIBLIOTECA) REFERENCES BIBLIOTECA(IDBIBLIOTECA);

ALTER TABLE LIVRO ADD CONSTRAINT FK_LIVRO_CATEGORIA
FOREIGN KEY (FK_IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA);

ALTER TABLE LIVRO ADD CONSTRAINT FK_LIVRO_BIBLIOTECA
FOREIGN KEY (FK_IDBIBLIOTECA) REFERENCES BIBLIOTECA(IDBIBLIOTECA);

ALTER TABLE EXEMPLAR ADD CONSTRAINT FK_EXEMPLAR_LIVRO
FOREIGN KEY (FK_IDLIVRO) REFERENCES LIVRO(IDLIVRO);

ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO_EXEMPLAR
FOREIGN KEY (FK_IDEXEMPLAR) REFERENCES EXEMPLAR(IDEXEMPLAR);

ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO_CLIENTE
FOREIGN KEY (FK_IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE MULTA ADD CONSTRAINT FK_MULTA_EMPRESTIMO
FOREIGN KEY (FK_IDEMPRESTIMO) REFERENCES EMPRESTIMO(IDEMPRESTIMO);
