-- PROJETO MYSQL BIBLIOTECAS
-- https://github.com/ErickVeronezi

CREATE DATABASE BIBLIOTECAS;

USE BIBLIOTECAS;

CREATE TABLE BIBLIOTECA(
	IDBIBLIOTECA INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	FK_IDBIBLIOTECA INT
);

CREATE TABLE CATEGORIA(
	IDCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(20),
	DESCRICAO TEXT
);

CREATE TABLE LIVRO(
	IDLIVRO INT PRIMARY KEY AUTO_INCREMENT,
	TITULO VARCHAR(50) NOT NULL,
	AUTOR VARCHAR(50) NOT NULL,
	EDITORA VARCHAR(50),
	ANO_PUBLICACAO YEAR NOT NULL,
	QUANTIDADE_DISPONIVEL INT NOT NULL,
	FK_IDCATEGORIA INT,
	FK_IDBIBLIOTECA INT
);

CREATE TABLE EXEMPLAR(
	IDEXEMPLAR INT PRIMARY KEY AUTO_INCREMENT,
	DISPONIVEL BOOLEAN DEFAULT TRUE,
	ESTADO_EXEMPLAR VARCHAR(20) NOT NULL,
	FK_IDLIVRO INT
);

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	CPF VARCHAR(11) UNIQUE NOT NULL,
	TIPO_USUARIO ENUM('ALUNO','PROFESSOR','EXTERNO'),
	DATA_CADASTRO DATE NOT NULL
);


CREATE TABLE EMPRESTIMO(
	IDEMPRESTIMO INT PRIMARY KEY AUTO_INCREMENT,
	DATA_EMPRESTIMO DATE NOT NULL,
	DATA_DEVOLUCAO DATE NOT NULL,
	STATUS ENUM('ABERTO', 'DEVOLVIDO', 'ATRASADO') NOT NULL,
	FK_IDCLIENTE INT,
	FK_IDEXEMPLAR INT
);


CREATE TABLE MULTA(
	IDMULTA INT PRIMARY KEY AUTO_INCREMENT,
	VALOR DECIMAL(10,2) NOT NULL,
	DATA_MULTA DATE NOT NULL,
	STATUS_PAGAMENTO ENUM('PAGO','PENDENTE') NOT NULL,
	FK_IDEMPRESTIMO INT
);



