-- PROJETO MYSQL BIBLIOTECAS
-- https://github.com/ErickVeronezi

INSERT INTO BIBLIOTECA (NOME) VALUES
('BIBLIOTECA CENTRAL'),
('BIBLIOTECA INFANTIL'),
('BIBLIOTECA ZONA SUL'),
('BIBLIOTECA UNIVERSITÁRIA');

INSERT INTO ENDERECO (RUA, BAIRRO, CIDADE, FK_IDBIBLIOTECA) VALUES
('RUA DAS LETRAS', 'CENTRO', 'SAO PAULO', 1),
('AV. DOS LIVROS', 'VILA NOVA', 'RIO DE JANEIRO', 2),
('RUA DA ALEGRIA','MOOCA','SAO PAULO', 4),
('TRAVESSA DO SABER', 'BOA VISTA', 'BELO HORIZONTE', 3);

INSERT INTO CATEGORIA (NOME, DESCRICAO) VALUES
('FICÇÃO', 'LIVROS DE FICÇÃO LITERÁRIA.'),
('CIÊNCIA', 'LIVROS CIENTÍFICOS E ACADÊMICOS.'),
('AUTOAJUDA','LIVROS PARA DESENVOLVIMENTO PESSOAL'),
('INFANTIL', 'LIVROS PARA O PÚBLICO INFANTIL.');

INSERT INTO LIVRO (TITULO, AUTOR, EDITORA, ANO_PUBLICACAO, QUANTIDADE_DISPONIVEL, FK_IDCATEGORIA, FK_IDBIBLIOTECA) VALUES
('A GUERRA DOS MUNDOS', 'H.G. WELLS', 'EDITORA ALFA', '1998', 5, 1, 1),
('FÍSICA MODERNA', 'STEPHEN JONES', 'EDITORA BETA', '2015', 3, 2, 3),
('O PEQUENO PRÍNCIPE', 'ANTOINE DE SAINT-EXUPÉRY', 'EDITORA GAMA', '1943', 7, 3, 2),
('O Alquimista', 'Paulo Coelho', 'Rocco', '1993', 3, 1, 1);

INSERT INTO EXEMPLAR (DISPONIVEL, ESTADO_EXEMPLAR, FK_IDLIVRO) VALUES
(TRUE, 'BOM', 1),
(TRUE, 'BOM', 1),
(FALSE, 'DAN', 1),
(TRUE, 'NOVO', 2),
(TRUE, 'BOM', 3),
(FALSE, 'DAN', 4);

INSERT INTO CLIENTE (NOME, EMAIL, CPF, TIPO_USUARIO, DATA_CADASTRO) VALUES
('JOÃO DA SILVA', 'JOAO@EMAIL.COM', '12345678900', 'ALUNO', '2024-07-01'),
('MARIA OLIVEIRA', 'MARIA@EMAIL.COM', '98765432100', 'PROFESSOR', '2024-07-02'),
('CARLOS SOUZA', 'CARLOS@EMAIL.COM', '11122233344', 'EXTERNO', '2024-07-03');

INSERT INTO EMPRESTIMO (DATA_EMPRESTIMO, DATA_DEVOLUCAO, STATUS, FK_IDCLIENTE, FK_IDEXEMPLAR) VALUES
('2024-07-10', '2024-07-20', 'ABERTO', 1, 1),
('2024-07-05', '2024-07-12', 'DEVOLVIDO', 2, 4),
('2024-07-15', '2024-07-25', 'ATRASADO', 3, 5);

INSERT INTO MULTA (VALOR, DATA_MULTA, STATUS_PAGAMENTO, FK_IDEMPRESTIMO) VALUES
(10, '2024-07-13', 'PENDENTE', 2),
(0, '2024-07-25', 'PAGO', 3);
