-- PROJETO MYSQL BIBLIOTECAS
-- https://github.com/ErickVeronezi



-- EMPRESTIMOS POR CLIENTE (MAIS FÁCIL PARA USAR DO QUE A VIEW)
DELIMITER $$

CREATE PROCEDURE P_EMPRESTIMOS_POR_CLIENTE(IN cliente_nome VARCHAR(50))
BEGIN
  SELECT 
    C.NOME,
    L.TITULO,
    E.DATA_EMPRESTIMO,
    E.DATA_DEVOLUCAO,
    E.STATUS
  FROM EMPRESTIMO E
  JOIN CLIENTE C ON E.FK_IDCLIENTE = C.IDCLIENTE
  JOIN EXEMPLAR EX ON E.FK_IDEXEMPLAR = EX.IDEXEMPLAR
  JOIN LIVRO L ON EX.FK_IDLIVRO = L.IDLIVRO
  WHERE C.NOME = cliente_nome;
END $$

DELIMITER ;
-- EXEMPLO PARA CHAMADAS: CALL P_EMPRESTIMOS_POR_CLIENTE('JOÃO DA SILVA');




-- ATUALIZAR STATUS DE UM EMPRESTIMO
DELIMITER $$

CREATE PROCEDURE P_ATUALIZAR_STATUS_EMPRESTIMO(IN IDEMP INT, IN NOVO_STATUS ENUM('ABERTO','DEVOLVIDO','ATRASADO'))
BEGIN
  UPDATE EMPRESTIMO
  SET STATUS = NOVO_STATUS
  WHERE IDEMPRESTIMO = IDEMP;
END $$

DELIMITER ;
-- EXEMPLO PARA CHAMADAS: CALL P_ATUALIZAR_STATUS_EMPRESTIMO(2, 'DEVOLVIDO');




-- REGISTRAR UMA NOVA MULTA
DELIMITER $$

CREATE PROCEDURE P_REGISTRAR_MULTA(IN IDEMP INT, IN VALOR DECIMAL(10,2))
BEGIN
  INSERT INTO MULTA (VALOR, DATA_MULTA, STATUS_PAGAMENTO, FK_IDEMPRESTIMO)
  VALUES (VALOR, CURDATE(), 'PENDENTE', IDEMP);
END $$

DELIMITER ;
-- EXEMPLO PARA CHAMADAS: CALL P_REGISTRAR_MULTA(1, 12.50);




-- MOSTRAR LIVROS DE UMA BIBLIOTECA ESPECÍFICA
DELIMITER $$

CREATE PROCEDURE P_LIVROS_POR_BIBLIOTECA(IN nome_biblioteca VARCHAR(50))
BEGIN
  SELECT 
    B.NOME AS BIBLIOTECA,
    L.TITULO,
    L.AUTOR,
    L.EDITORA,
    L.ANO_PUBLICACAO,
    L.QUANTIDADE_DISPONIVEL
  FROM LIVRO L
  JOIN BIBLIOTECA B ON L.FK_IDBIBLIOTECA = B.IDBIBLIOTECA
  WHERE B.NOME = nome_biblioteca;
END $$

DELIMITER ;
-- EXEMPLO PARA CHAMADAS: CALL P_LIVROS_POR_BIBLIOTECA('BIBLIOTECA CENTRAL');



-- LISTAR TODAS MULTAS ASSOCIADAS A UM CLIENTE (FILTRANDO PELO NOME)
DELIMITER $$

CREATE PROCEDURE P_LISTAR_MULTAS_CLIENTE(IN nomeCliente VARCHAR(50))
BEGIN
  SELECT 
    C.NOME,
    M.VALOR,
    M.DATA_MULTA,
    M.STATUS_PAGAMENTO
  FROM CLIENTE C
  JOIN EMPRESTIMO E ON E.FK_IDCLIENTE = C.IDCLIENTE
  JOIN MULTA M ON M.FK_IDEMPRESTIMO = E.IDEMPRESTIMO
  WHERE C.NOME = nomeCliente;
END $$

DELIMITER ;
-- EXEMPLO PARA CHAMADAS: CALL P_LISTAR_MULTAS_CLIENTE('MARIA OLIVEIRA');
