-- PROJETO MYSQL BIBLIOTECAS
-- https://github.com/ErickVeronezi


-- LIVROS DE CADA BIBLIOTECA E QUANTIDADES DISPONIVEIS
CREATE VIEW V_TOTAL_LIVROS AS
SELECT 	B.IDBIBLIOTECA,
		B.NOME,
		L.TITULO,
		L.AUTOR,
		L.ANO_PUBLICACAO,
		L.QUANTIDADE_DISPONIVEL
FROM BIBLIOTECA B
LEFT JOIN LIVRO L
ON B.IDBIBLIOTECA = L.FK_IDBIBLIOTECA
ORDER BY B.NOME;

-- CLIENTES COM EMPRESTIMO ABERTO E ATRASADO
CREATE VIEW V_EMPRESTIMO_ABERTO AS
SELECT 	C.NOME,
		C.EMAIL,
		C.TIPO_USUARIO,
		E.DATA_EMPRESTIMO,
		E.DATA_DEVOLUCAO,
		E.STATUS
FROM CLIENTE C
JOIN EMPRESTIMO E
ON E.FK_IDCLIENTE = C.IDCLIENTE
WHERE STATUS = 'ATRASADO' OR STATUS = 'ABERTO';

-- CLIENTES COM EMPRESTIMO APENAS ATRASADO
CREATE VIEW V_EMPRESTIMOS_ATRASADO AS
SELECT 	C.NOME,
		C.EMAIL,
		C.TIPO_USUARIO,
		E.DATA_EMPRESTIMO,
		E.DATA_DEVOLUCAO,
		E.STATUS
FROM CLIENTE C
JOIN EMPRESTIMO E
ON E.FK_IDCLIENTE = C.IDCLIENTE
WHERE STATUS = 'ATRASADO';



-- EMPRESTIMOS POR CLIENTE
CREATE VIEW V_TOTAL_EMPRESTIMOS AS
SELECT 	C.NOME,
		C.EMAIL,
		C.TIPO_USUARIO,
		E.DATA_EMPRESTIMO,
		E.DATA_DEVOLUCAO,
		E.STATUS
FROM CLIENTE C
JOIN EMPRESTIMO E
ON E.FK_IDCLIENTE = C.IDCLIENTE;

/* LEMBRANDO QUE NA HORA DE CHAMAR A VIEW (V_TOTAL_EMPRESTIMOS), ADICIONAR O FILTRO WHERE
EX: SELECT * 	FROM V_TOTAL_EMPRESTIMOS
				WHERE NOME 'MARIA OLIVEIRA'*/


-- LIVROS DISPONIVEIS
CREATE VIEW V_LIVROS_DISPONIVEIS AS
SELECT 	L.TITULO,
		L.AUTOR,L.EDITORA,
		COUNT(E.IDEXEMPLAR) AS EXEMPLARES_DISPONIVEIS
FROM LIVRO L
JOIN EXEMPLAR E ON L.IDLIVRO = E.FK_IDLIVRO
WHERE E.DISPONIVEL = TRUE
GROUP BY L.IDLIVRO;


-- MULTAS EM ABERTO
CREATE VIEW V_TOTAL_MULTA AS
SELECT 	C.NOME,
		C.EMAIL,
		M.VALOR,
		M.DATA_MULTA,
		M.STATUS_PAGAMENTO
FROM CLIENTE C
JOIN EMPRESTIMO E
ON E.FK_IDCLIENTE = C.IDCLIENTE
JOIN MULTA M
ON M.FK_IDEMPRESTIMO = E.IDEMPRESTIMO
WHERE STATUS_PAGAMENTO = 'PENDENTE'; 